### ISSUE TITLE
Compiling fltk-sys v1.0.0

### ISSUE THREAD

**Issue by grigmily** [tdryer/7guis-fltk-rs#2]
> > `Compiling fltk-sys v1.0.0
> error: failed to run custom build command for `fltk-sys v1.0.0`
> 
> Caused by:
>   process didn't exit successfully: `/var/home/***/7guis-fltk-rs-master/target/debug/build/fltk-sys-e7cde9c05d985e68/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=build.rs
>   cargo:rerun-if-env-changed=CC
>   cargo:rerun-if-env-changed=CXX
>   cargo:rerun-if-changed=cfltk/CMakeLists.txt
>   cargo:rerun-if-changed=cfltk/include/cfl.h
>   cargo:rerun-if-changed=cfltk/include/cfl_widget.h
>   cargo:rerun-if-changed=cfltk/include/cfl_group.h
>   cargo:rerun-if-changed=cfltk/include/cfl_input.h
>   cargo:rerun-if-changed=cfltk/include/cfl_output.h
>   cargo:rerun-if-changed=cfltk/include/cfl_window.h
>   cargo:rerun-if-changed=cfltk/include/cfl_button.h
>   cargo:rerun-if-changed=cfltk/include/cfl_box.h
>   cargo:rerun-if-changed=cfltk/include/cfl_menu.h
>   cargo:rerun-if-changed=cfltk/include/cfl_dialog.h
>   cargo:rerun-if-changed=cfltk/include/cfl_valuator.h
>   cargo:rerun-if-changed=cfltk/include/cfl_browser.h
>   cargo:rerun-if-changed=cfltk/include/cfl_misc.h
>   cargo:rerun-if-changed=cfltk/include/cfl_text.h
>   cargo:rerun-if-changed=cfltk/include/cfl_image.h
>   cargo:rerun-if-changed=cfltk/include/cfl_draw.h
>   cargo:rerun-if-changed=cfltk/include/cfl_table.h
>   cargo:rerun-if-changed=cfltk/include/cfl_surface.h
>   cargo:rerun-if-changed=cfltk/include/cfl_printer.h
>   cargo:rerun-if-changed=cfltk/src/cfl_global.hpp
>   cargo:rerun-if-changed=cfltk/src/cfl_new.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_widget.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_group.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_window.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_button.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_box.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_menu.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_dialog.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_valuator.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_browser.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_misc.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_text.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_image.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_input.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_output.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_draw.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_table.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_tree.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_surface.cpp
>   cargo:rerun-if-changed=cfltk/src/cfl_printer.cpp
>   running: "cmake" "/var/home/*user*/.cargo/registry/src/github.com-1ecc6299db9ec823/fltk-sys-1.0.0/cfltk" "-DOPTION_USE_SYSTEM_LIBPNG=OFF" "-DOPTION_USE_SYSTEM_LIBJPEG=OFF" "-DOPTION_USE_SYSTEM_ZLIB=OFF" "-DCFLTK_LINK_IMAGES=ON" "-DOpenGL_GL_PREFERENCE=GLVND" "-DOPTION_USE_GL=OFF" "-DCFLTK_USE_OPENGL=OFF" "-DOPTION_USE_PANGO=ON" "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" "-DFLTK_BUILD_EXAMPLES=OFF" "-DFLTK_BUILD_TEST=OFF" "-DOPTION_USE_THREADS=ON" "-DOPTION_LARGE_FILE=ON" "-DOPTION_BUILD_HTML_DOCUMENTATION=OFF" "-DOPTION_BUILD_PDF_DOCUMENTATION=OFF" "-DCMAKE_INSTALL_PREFIX=/var/home/***/7guis-fltk-rs-master/target/debug/build/fltk-sys-a9cedecbd0b45946/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/lib64/ccache/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/lib64/ccache/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/lib64/ccache/cc" "-DCMAKE_BUILD_TYPE=Release"
>   -- Could NOT find LATEX (missing: LATEX_COMPILER) 
>   -- Pango requires Xft but Xft library or headers could not be found.
>   -- Please install Xft development files and try again or disable OPTION_USE_PANGO.
>   -- Configuring incomplete, errors occurred!
>   See also "/var/home/***/7guis-fltk-rs-master/target/debug/build/fltk-sys-a9cedecbd0b45946/out/build/CMakeFiles/CMakeOutput.log".
>   See also "/var/home/***/7guis-fltk-rs-master/target/debug/build/fltk-sys-a9cedecbd0b45946/out/build/CMakeFiles/CMakeError.log".
> 
>   --- stderr
>   fatal: not a git repository (or any parent up to mount point /var/home)
>   Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
>   CMake Error at fltk/CMake/options.cmake:479 (message):
>     *** Aborting ***
>   Call Stack (most recent call first):
>     fltk/CMakeLists.txt:79 (include)
> 
> 
>   thread 'main' panicked at '
>   command did not execute successfully, got: exit status: 1
> 
>   build script failed, must exit now', /var/home/*user*/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by tdryer** [comment]
See here for dependencies required to build fltk:
https://github.com/fltk-rs/fltk-rs/blob/master/README.md#dependencies
